# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'After Next Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Cosmos'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'lottie-ios'
pod 'SwiftGifOrigin', '~> 1.7.0'
  # Pods for After Next Player

end
